"use strict";

module.exports = {
  JobStatus: {
    requested: "requested",
    running: "running",
    completed: "completed",
    completedWithWarning: "completedWithWarning",
    completedWithError: "completedWithError",
    failed: "failed",
    cancelRequested: "cancelRequested",
    canceled: "canceled",
  },
  ParameterType: {
    readOnlyValue: "readOnlyValue",
    writableValue: "writableValue",
    mapping: "mapping",
  },
  DataType: {
    string: "string",
    number: "number",
    date: "date",
    datetime: "datetime",
    boolean: "boolean",
  },
  MappingType: {
    accountingPrinciple: "accountingPrinciple",
    companyCode: "companyCode",
    plant: "plant",
    controllingArea: "controllingArea",
    fiscalPeriod: "fiscalPeriod",
    fiscalYearPeriod: "fiscalYearPeriod",
    fiscalYear: "fiscalYear",
    keyDate: "keyDate",
    chartOfAccounts: "chartOfAccounts",
    fiscalYearVariant: "fiscalYearVariant",
    ledger: "ledger",
    testRun: "testRun",
    postingPeriodVariant: "postingPeriodVariant",
    processingUser: "processingUser",
    interestedUser: "interestedUser",
    userResponsible: "userResponsible",
    processingUserEmail: "processingUserEmail",
    interestedUserEmail: "interestedUserEmail",
    userResponsibleEmail: "userResponsibleEmail",
    executionID: "executionID",
    customField1: "customField1",
    customField2: "customField2",
    customField3: "customField3",
    taskListID: "taskListID",
    taskListDescription: "taskListDescription",
    taskID: "taskID",
    taskDescription: "taskDescription",
  },
  ResultType: {
    link: "link",
    data: "data",
    message: "message",
  },
  MessageSeverity: {
    success: "success",
    info: "info",
    warning: "warning",
    error: "error",
  },
  MessageSeverityNumeric: {
    success: 1,
    info: 2,
    warning: 3,
    error: 4,
  },
};
