name: "kyma-setup"

description: "Installs the Kyma dependencies"

inputs:
  imageRegistry:
    description: Image Registry
    required: true
  user:
    description: Artifactory User
    required: true
  password:
    description: Artifactory Password
    required: true
  kubeConfig:
    description: Kube Config
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Helm
      uses: azure/setup-helm@v4
    - name: Install Containerize
      run: npm install -g ctz
      shell: bash
    - name: Login Docker
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.imageRegistry }}
        username: ${{ inputs.user }}
        password: ${{ inputs.password }}
    - name: Setup Tools
      uses: buildpacks/github-actions/setup-tools@v5.1.0
    - name: Setup Pack
      uses: buildpacks/github-actions/setup-pack@v5.1.0
    - name: Setup Kube
    - run: |
        mkdir ${HOME}/kyma-binaries
        export PATH=${HOME}/kyma-binaries/:$PATH
        mkdir ${HOME}/.kube
        echo "${{ inputs.kubeConfig }}" > ${HOME}/.kube/config
      shell: bash
