name: "kyma-setup"

description: "Installs the Kyma dependencies"

inputs:
  kubeConfig:
    description: Kube Config
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Helm
      uses: azure/setup-helm@v4
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v4
    - name: Install Containerize
      run: npm install -g ctz
      shell: bash
    - name: Setup Tools
      uses: buildpacks/github-actions/setup-tools@v5.8.10
    - name: Setup Pack
      uses: buildpacks/github-actions/setup-pack@v5.8.10
    - name: Setup Kube
      run: |
        mkdir ${HOME}/kyma-binaries
        export PATH=${HOME}/kyma-binaries/:$PATH
        mkdir ${HOME}/.kube
        echo "${{ inputs.kubeConfig }}" > ${HOME}/.kube/config
      shell: bash
