name: "kyma-setup"

description: "Installs the Kyma dependencies"

inputs:
  imageRegistry:
    description: Image Registry
    required: true
  user:
    description: Artifactory User
    required: true
  password:
    description: Artifactory Password
    required: true
  kubeConfig:
    description: Kube Config
    required: true

runs:
  using: "composite"
  steps:
    - run: sudo apt-get update -y
      shell: bash
    - run: sudo apt-get install -y ca-certificates curl gnupg
      shell: bash
    - run: sudo install -m 0755 -d /etc/apt/keyrings
      shell: bash
    - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
      shell: bash
    - run: sudo chmod a+r /etc/apt/keyrings/docker.asc
      shell: bash
    - run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      shell: bash
    - run: sudo apt-get update -y
      shell: bash
    - run: sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      shell: bash
    - run: sudo apt-get install helm -y
      shell: bash
    - run: npm install -g ctz
      shell: bash
    - run: |
        mkdir ${HOME}/kyma-binaries
        export PATH=${HOME}/kyma-binaries/:$PATH
        echo "${{ inputs.password }}" | docker login "${{ inputs.imageRegistry }}" -u "${{ inputs.user }}" --password-stdin
        mkdir ${HOME}/.kube
        echo "${{ inputs.kubeConfig }}" > ${HOME}/.kube/config
      shell: bash
