name: "kyma-setup"

description: "Installs the Kyma dependencies"

inputs:
  imageRegistry:
    description: Image Registry
    required: true
  user:
    description: Artifactory User
    required: true
  password:
    description: Artifactory Password
    required: true
  kubeConfig:
    description: Kube Config
    required: true

runs:
  using: "composite"
  steps:
    - run: sudo apt-get update -y
      shell: bash
    - run: sudo apt-get install docker.io -y
      shell: bash
    - run: sudo apt-get install kubectl -y
      shell: bash
    - run: sudo apt-get install helm
      shell: bash
    - run: npm install -g ctz
      shell: bash
    - run: |
        mkdir ${HOME}/kyma-binaries
        export PATH=${HOME}/kyma-binaries/:$PATH
        echo "${{ inputs.password }}" | docker login "${{ inputs.imageRegistry }}" -u "${{ inputs.user }}" --password-stdin
        mkdir ${HOME}/.kube
        echo "${{ inputs.kubeConfig }}" > ${HOME}/.kube/config
      shell: bash
