name: "kyma-setup"

description: "Installs the Kyma dependencies"

inputs:
  imageRegistry:
    description: Image Registry
    required: true
  user:
    description: Artifactory User
    required: true
  password:
    description: Artifactory Password
    required: true
  kubeConfig:
    description: Kube Config
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Helm
      uses: azure/setup-helm@v4
    - name: Install Containerize
      run: npm install -g ctz
    - name: Install Pack CLI
      uses: buildpacks/github-actions/setup-pack@v5
    - run: |
        mkdir ${HOME}/kyma-binaries
        export PATH=${HOME}/kyma-binaries/:$PATH
        echo "${{ inputs.password }}" | docker login "${{ inputs.imageRegistry }}" -u "${{ inputs.user }}" --password-stdin
        mkdir ${HOME}/.kube
        echo "${{ inputs.kubeConfig }}" > ${HOME}/.kube/config
      shell: bash
