@host=<server host from cloud deployment>
@internalToken=<xsuaa internal token>

### Feature Toggles state
GET https://{{host}}/rest/feature/state
Authorization: Bearer {{internalToken}}

### Event Queue active
POST https://{{host}}/rest/feature/redisUpdate
Authorization: Bearer {{internalToken}}
Content-Type: application/json

{
  "key": "eventQueue/active",
  "value": false
}

### Event Queue instance load limit
POST https://{{host}}/rest/feature/redisUpdate
Authorization: Bearer {{internalToken}}
Content-Type: application/json

{
  "key": "eventQueue/instanceLoadLimit",
  "value": 11
}

### Remove: Event Queue active
POST https://{{host}}/rest/feature/redisUpdate
Authorization: Bearer {{internalToken}}
Content-Type: application/json

{
  "key": "eventQueue/active",
  "value": null,
  "options": {
    "clearSubScopes": true
  }
}

### Remove: Event Queue instance load limit
POST https://{{host}}/rest/feature/redisUpdate
Authorization: Bearer {{internalToken}}
Content-Type: application/json

{
  "key": "eventQueue/instanceLoadLimit",
  "value": null,
  "options": {
    "clearSubScopes": true
  }
}
