@hostname=<add your own hostname from cloud deployment>
@token=<add your token from xsuaa>

### Feature Toggles state
GET https://{{hostname}}/rest/feature/state
Authorization: Bearer {{token}}

### Event Queue active
POST https://{{hostname}}/rest/feature/redisUpdate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "eventQueue/active",
  "value": false
}

### Event Queue instance load limit
POST https://{{hostname}}/rest/feature/redisUpdate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "eventQueue/instanceLoadLimit",
  "value": 11
}

### Remove: Event Queue active
POST https://{{hostname}}/rest/feature/redisUpdate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "eventQueue/active",
  "value": null,
  "options": {
    "clearSubScopes": true
  }
}

### Remove: Event Queue instance load limit
POST https://{{hostname}}/rest/feature/redisUpdate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "eventQueue/instanceLoadLimit",
  "value": null,
  "options": {
    "clearSubScopes": true
  }
}
