name: "cf-setup"

description: "Installs CF CLI."

inputs:
  cf-version:
    description: "Full CF CLI version, e.g. 8"
    required: false
    default: "8"

  api:
    description: "CF api"
    required: false
    default: https://api.cf.eu12.hana.ondemand.com

  org:
    description: "CF org"
    required: true

  space:
    description: "CF space"
    required: true

runs:
  using: node20
  main: ./setup.js
