@api=<api endpoint from cloud deployment>
@token=<xsuaa token>

### Job Definition
GET https://{{api}}/job-scheduling/v1/JobDefinition
Authorization: Bearer {{token}}

### Job Definition Parameters
GET https://{{api}}/job-scheduling/v1/JobDefinition/JOB_1/parameters
Authorization: Bearer {{token}}

### Job
GET https://{{api}}/job-scheduling/v1/Job
Authorization: Bearer {{token}}

### Job Parameters
GET https://{{api}}/job-scheduling/v1/Job/3a89dfec-59f9-4a91-90fe-3c7ca7407103/parameters
Authorization: Bearer {{token}}

### Job Results
GET http://{{api}}/job-scheduling/v1/Job/5a89dfec-59f9-4a91-90fe-3c7ca7407103/results
Authorization: Bearer {{token}}

### Job Result Messages
GET http://{{api}}/job-scheduling/v1/JobResult/c2eb590f-9505-4fd6-a5e2-511a1b2ff47f/messages
Authorization: Bearer {{token}}

### Job Result Message Data
GET http://{{api}}/job-scheduling/v1/JobResult/b2eb590f-9505-4fd6-a5e2-511a1b2ff47f/data
Authorization: Bearer {{token}}

### Create Job
POST https://{{api}}/job-scheduling/v1/Job
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "JOB_1",
    "referenceID": "abc4711",
    "parameters": [{
        "name": "A",
        "value": "abc"
      },
      {
        "name": "B",
        "value": "21"
      },
      {
        "name": "C",
        "value": "false"
      },
      {
        "name": "D",
        "value": "11.12"
      },
      {
        "name": "E",
        "value": "2025-01-01T12:00:00Z"
      }
    ]
}

### Cancel Job
POST https://{{api}}/job-scheduling/v1/Job/3a89dfec-59f9-4a91-90fe-3c7ca7407103/cancel
Authorization: Bearer {{token}}
Content-Type: application/json

### Notification
POST https://{{api}}/job-scheduling/v1/notify
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "notifications": [
    {
      "name": "taskListStatusChanged",
      "ID": "1a89dfec-59f9-4a91-90fe-3c7ca7407103",
      "value": "obsolete"
    }
  ]
}