@api=<api endpoint from cloud deployment>
@token=<xsuaa token>

@job=JOB_1
@jobId=<uuid of a job>
@jobResultId=<uuid of a job result>

### Job Definitions
GET https://{{api}}/job-scheduling/v1/JobDefinition
Authorization: Bearer {{token}}

### Job Definition
GET https://{{api}}/job-scheduling/v1/JobDefinition/{{job}}
Authorization: Bearer {{token}}

### Job Definition Parameters
GET https://{{api}}/job-scheduling/v1/JobDefinition/{{job}}/parameters
Authorization: Bearer {{token}}

### Jobs
GET https://{{api}}/job-scheduling/v1/Job
Authorization: Bearer {{token}}

### Job
GET https://{{api}}/job-scheduling/v1/Job/{{jobId}}
Authorization: Bearer {{token}}

### Job Parameters
GET https://{{api}}/job-scheduling/v1/Job/{{jobId}}/parameters
Authorization: Bearer {{token}}

### Job Results
GET http://{{api}}/job-scheduling/v1/Job/{{jobId}}/results
Authorization: Bearer {{token}}

### Job Result Messages
GET http://{{api}}/job-scheduling/v1/JobResult/{{jobResultId}}/messages
Authorization: Bearer {{token}}

### Job Result Message Data
GET http://{{api}}/job-scheduling/v1/JobResult/{{jobResultId}}/data
Authorization: Bearer {{token}}

### Create Job
POST https://{{api}}/job-scheduling/v1/Job
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "{{job}}",
  "referenceID": "b001397c-b7f9-4f03-ba79-ec11297cae81",
  "parameters": [
    {
      "name": "A",
      "value": "abc"
    },
    {
      "name": "B",
      "value": 21
    },
    {
      "name": "C",
      "value": false
    },
    {
      "name": "D",
      "value": "11.12"
    },
    {
      "name": "E",
      "value": "2025-01-01T12:00:00Z"
    }
  ]
}

### Cancel Job
POST https://{{api}}/job-scheduling/v1/Job/{{jobId}}/cancel
Authorization: Bearer {{token}}
Content-Type: application/json

### Notification
POST https://{{api}}/job-scheduling/v1/notify
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "notifications": [
    {
      "name": "taskListStatusChanged",
      "ID": "1a89dfec-59f9-4a91-90fe-3c7ca7407103",
      "code": "TASKLIST-1",
      "value": "obsolete"
    }
  ]
}