@port=4004
@host=localhost:{{port}}
@username=alice
@password=alice

@job=JOB_1
@jobId=<uuid of a job>
@jobResultId=<uuid of a job result>

### Job Definitions
GET http://{{host}}/api/job-scheduling/v1/JobDefinition
Authorization: Basic {{username}} {{password}}

### Job Definition
GET http://{{host}}/api/job-scheduling/v1/JobDefinition/{{job}}
Authorization: Basic {{username}} {{password}}

### Job Definition Parameters
GET http://{{host}}/api/job-scheduling/v1/JobDefinition/{{job}}/parameters
Authorization: Basic {{username}} {{password}}

### Jobs
GET http://{{host}}/api/job-scheduling/v1/Job
Authorization: Basic {{username}} {{password}}

### Job
GET http://{{host}}/api/job-scheduling/v1/Job/{{jobId}}
Authorization: Basic {{username}} {{password}}

### Job Parameters
GET http://{{host}}/api/job-scheduling/v1/Job/{{jobId}}/parameters
Authorization: Basic {{username}} {{password}}

### Job Results
GET http://{{host}}/api/job-scheduling/v1/Job/{{jobId}}/results
Authorization: Basic {{username}} {{password}}

### Job Result Messages
GET http://{{host}}/api/job-scheduling/v1/JobResult/{{jobResultId}}/messages
Authorization: Basic {{username}} {{password}}

### Job Result Message Data
GET http://{{host}}/api/job-scheduling/v1/JobResult/{{jobResultId}}/data
Authorization: Basic {{username}} {{password}}

### Create Job
POST http://{{host}}/api/job-scheduling/v1/Job
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "name": "{{job}}",
  "referenceID": "b001397c-b7f9-4f03-ba79-ec11297cae81",
  "parameters": [
    {
      "name": "A",
      "value": "abc"
    },
    {
      "name": "B",
      "value": 21
    },
    {
      "name": "C",
      "value": false
    },
    {
      "name": "D",
      "value": "11.12"
    },
    {
      "name": "E",
      "value": "2025-01-01T12:00:00Z"
    }
  ]
}

### Cancel Job
POST http://{{host}}/api/job-scheduling/v1/Job/{{jobId}}/cancel
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

### Notification
POST http://{{host}}/api/job-scheduling/v1/notify
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "notifications": [
    {
      "name": "taskListStatusChanged",
      "ID": "1a89dfec-59f9-4a91-90fe-3c7ca7407103",
      "value": "obsolete"
    }
  ]
}